export { ProductSwitcher } from './ProductSwitcher';
export { BundleSelector } from './BundleSelector';
export { InstallationSelector } from './InstallationSelector';
export { ProductLightbox } from './ProductLightbox';
export { MaterialPerspectivesViewer } from './MaterialPerspectivesViewer';
export { HeroSection } from './HeroSection';
export { ProductStorySection } from './ProductStorySection';
export { KeyBenefitsSection } from './KeyBenefitsSection';
export { TechnicalOverview } from './TechnicalOverview';
export { ApplicationSection } from './ApplicationSection';
export { ResistanceParameters } from './ResistanceParameters';
export { LogisticsSection } from './LogisticsSection';
export { ArchitectBlock } from './ArchitectBlock';
export { ProductFAQSection } from './ProductFAQSection';
export { ProductSchema } from './ProductSchema';
export type { BundleOption } from './types';
export { BUNDLE_OPTIONS, INSTALLATION_RATE_PER_M2, INSTALLATION_STORAGE_KEY, saveInstallationToStorage, loadInstallationFromStorage } from './types';
export { calculateSlabPrice, shopifyImageUrl, shopifySrcSet, productImageAlt, shortFinish, getFinishIcon, ThicknessIcon } from './utils';
